### ISSUE TITLE
Add webhook

### ISSUE THREAD

**Issue by nealsanche** [awigglesworth/WardensSite#2]
So, you also need to add a webhook using the following procedure.

1) Go to Settings > Webhooks
2) Add a new webhook with the following info:
  - Payload URL: https://wardens.nosuch.dev
  - Content Type: application/json
  - Secret: wardensecret
  - Enable SSL Verification
  - Just the `push` event

That should be all you need to do, and this will enable updates, as long as the deployment key is also added.

**Comment by awigglesworth** [comment]
Done
